# Generated by Django 4.2.1 on 2023-05-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_videoelement_duration_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBlock',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('video_component_id', models.CharField(max_length=50, null=True)),
                ('high_volume', models.IntegerField()),
                ('low_volume', models.IntegerField()),
                ('duration_start_time', models.IntegerField()),
                ('duration_end_time', models.IntegerField()),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('audio_id', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('duration_start_time', models.IntegerField()),
                ('duration_end_time', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AudioElement',
        ),
        migrations.DeleteModel(
            name='AudioFragments',
        ),
        migrations.DeleteModel(
            name='VideoElement',
        ),
    ]
