# Generated by Django 4.2.1 on 2023-05-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_audioblock_videoblock_delete_audioelement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoblock',
            name='duration_end_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='videoblock',
            name='duration_start_time',
            field=models.IntegerField(null=True),
        ),
    ]
