# Generated by Django 4.2.1 on 2023-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_videoblock_duration_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioblock',
            name='duration_end_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='audioblock',
            name='duration_start_time',
            field=models.IntegerField(null=True),
        ),
    ]
