# Generated by Django 4.2.1 on 2023-05-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_audioblock_duration_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedData',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('audio_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.audioblock')),
                ('video_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.videoblock')),
            ],
        ),
    ]
