# Generated by Django 4.2.1 on 2023-05-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mergeddata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MergedData',
            new_name='AudioElements',
        ),
    ]
