# Generated by Django 4.2.1 on 2023-05-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_mergeddata_audioelements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioelements',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
