# Generated by Django 4.2.1 on 2023-05-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_audioelements_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioblock',
            name='duration_end_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='audioblock',
            name='duration_start_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='audioblock',
            name='id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videoblock',
            name='duration_end_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='videoblock',
            name='duration_start_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='videoblock',
            name='id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
